# Only explicitly selected hardware components participate in this build.
set(COMPONENTS main)
set(IDF_TARGET esp32s3 CACHE STRING "Supported target")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_NINJA_FORCE_RESPONSE_FILE ON)
get_filename_component(HW_COMPONENTS "${CMAKE_CURRENT_LIST_DIR}/../components" ABSOLUTE)
set(EXTRA_COMPONENT_DIRS "${HW_COMPONENTS}/sdk/watche_hw_core")
if(HW_BODY)
  foreach(name mcu_motion_service mcu_led_service mcu_sensor_service mcu_power_service motion_arbiter mcu_runtime)
    list(APPEND EXTRA_COMPONENT_DIRS "${HW_COMPONENTS}/services/${name}")
  endforeach()
  list(APPEND EXTRA_COMPONENT_DIRS "${HW_COMPONENTS}/protocols/mcu_link" "${HW_COMPONENTS}/sdk/watche_hw_body")
endif()
if(HW_HEAD)
  foreach(name sensecap-watcher esp_lvgl_port esp_io_expander_pca95xx_16bit sscma_client watcher_hx_ptl hx_media_protocol hx_ptl_protocol jpeg_integrity)
    list(APPEND EXTRA_COMPONENT_DIRS "${HW_COMPONENTS}/${name}")
  endforeach()
  list(APPEND EXTRA_COMPONENT_DIRS "${HW_COMPONENTS}/services/watcher_input_router")
  foreach(name audio camera)
    list(APPEND EXTRA_COMPONENT_DIRS "${HW_COMPONENTS}/hal/hal_${name}" "${HW_COMPONENTS}/sdk/watche_hw_${name}")
  endforeach()
  list(APPEND EXTRA_COMPONENT_DIRS "${HW_COMPONENTS}/sdk/watche_hw_display")
endif()
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
function(watche_hw_check_idf)
  idf_build_get_property(IDF_VERSION IDF_VER)
  string(REGEX REPLACE "^v" "" IDF_VERSION "${IDF_VERSION}")
  if(NOT IDF_VERSION VERSION_EQUAL "6.0.2")
    message(FATAL_ERROR "Hardware SDK requires ESP-IDF 6.0.2, got ${IDF_VERSION}")
  endif()
  add_compile_definitions(MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS)
  foreach(name button knob)
    if(TARGET idf::espressif__${name})
      target_link_libraries(__idf_espressif__${name} PUBLIC idf::esp_driver_gpio)
    endif()
  endforeach()
  if(TARGET idf::espressif__led_strip)
    target_link_libraries(__idf_espressif__led_strip PUBLIC idf::esp_driver_rmt idf::esp_driver_spi idf::esp_hal_gpspi idf::heap)
  endif()
endfunction()

